import os
import re
import sys

import gitlab

GENERATED_BY_BOT_NOTE = "Generated By Changesets Bot"

RANDOM_BOT_NAME_PATTERN = re.compile(
    r"^((?:project|group)_\d+_bot\w*)_[\da-z]+$", re.IGNORECASE
)


def _get_release_plan_table() -> str:
    """Build a markdown table of packages and their bump types from .changeset/ files."""
    from changeset.changeset import get_changesets

    changesets = get_changesets()
    if not changesets:
        return ""

    _bump_rank = {"major": 3, "minor": 2, "patch": 1}
    packages: dict[str, str] = {}
    for _, package, change_type, _ in changesets:
        current = packages.get(package)
        if current is None or _bump_rank[change_type] > _bump_rank[current]:
            packages[package] = change_type

    labels = {"major": "Major 💥", "minor": "Minor ✨", "patch": "Patch 🐛"}
    rows = "\n".join(
        f"| `{pkg}` | {labels[bump]} |"
        for pkg, bump in sorted(packages.items())
    )
    return (
        "<details><summary>Packages affected</summary>\n\n"
        "| Package | Bump type |\n"
        "| --- | --- |\n"
        f"{rows}\n\n"
        "</details>"
    )


class Comment:
    def __init__(self, gl: gitlab.Gitlab):
        self.gl = gl
        self.project_id = os.getenv("CI_PROJECT_ID")
        self.mr_branch = os.getenv("CI_MERGE_REQUEST_SOURCE_BRANCH_NAME")

    def absent_changeset_comment(self, commit_sha: str) -> str:
        return f"""###  ⚠️  No Changeset found

Latest commit: {commit_sha}

Merging this MR will not cause a version bump for any packages. If these changes should not result in a new version, you're good to go. **If these changes should result in a version bump, you need to add a changeset.**

To add a changeset, run:

```
pychangeset add
```

Then commit and push the generated file under `.changeset/`.

__{GENERATED_BY_BOT_NOTE}__
"""

    def approve_changeset_comment(self, commit_sha: str) -> str:
        table = _get_release_plan_table()
        return f"""###  🦋  Changeset detected

Latest commit: {commit_sha}

**The changes in this MR will be included in the next version bump.**

{table}

__{GENERATED_BY_BOT_NOTE}__
"""

    def _is_bot_comment(self, note, username: str, random: bool = False) -> bool:
        note_username = note.author["username"]
        username_match = note_username == username or (
            random
            and (m := RANDOM_BOT_NAME_PATTERN.match(note_username)) is not None
            and m.group(1) == username
        )
        return username_match and GENERATED_BY_BOT_NOTE in note.body

    def find_bot_comment(self, mr_iid: int, username: str):
        project = self.gl.projects.get(self.project_id)
        merge_request = project.mergerequests.get(mr_iid)
        notes = merge_request.notes.list(get_all=True)
        # First pass: exact username match
        for note in notes:
            if self._is_bot_comment(note, username, random=False):
                return note
        # Second pass: random bot suffix (project_N_bot_<suffix>)
        # https://docs.gitlab.com/ee/development/internal_users.html
        for note in notes:
            if self._is_bot_comment(note, username, random=True):
                return note
        return None

    def create_or_update_comment(self, mr_iid: int, username: str, comment_body: str):
        existing_comment = self.find_bot_comment(mr_iid, username)
        project = self.gl.projects.get(self.project_id)
        merge_request = project.mergerequests.get(mr_iid)

        if existing_comment:
            existing_comment.body = comment_body
            existing_comment.save()
        else:
            merge_request.notes.create({"body": comment_body})

    def has_changeset_been_added(self, mr_iid: int) -> bool:
        project = self.gl.projects.get(self.project_id)
        merge_request = project.mergerequests.get(mr_iid)
        changes_data = merge_request.changes()
        for change in changes_data.get("changes", []):
            if (
                change.get("new_file")
                and re.match(r"^\.changeset/.+\.md$", change["new_path"])
                and change["new_path"] != ".changeset/README.md"
            ):
                return True
        return False

    def run(self):
        if not self.mr_branch:
            print(
                "[pychangeset:comment] It should only be used on MR",
                file=sys.stderr,
            )
            return

        if self.mr_branch.startswith("changeset-release"):
            return

        mr_iid_str = os.getenv("CI_MERGE_REQUEST_IID")
        if not mr_iid_str:
            print(
                "[pychangeset:comment] CI_MERGE_REQUEST_IID not set",
                file=sys.stderr,
            )
            return

        mr_iid = int(mr_iid_str)
        commit_sha = os.getenv("CI_MERGE_REQUEST_SOURCE_BRANCH_SHA", "")

        self.gl.auth()
        username = self.gl.user.username

        has_changeset = self.has_changeset_been_added(mr_iid)

        body = (
            self.approve_changeset_comment(commit_sha)
            if has_changeset
            else self.absent_changeset_comment(commit_sha)
        )

        self.create_or_update_comment(mr_iid, username, body)


def comment():
    """Post or update a changeset status comment on the current MR."""
    server_url = os.getenv("CI_SERVER_URL", "https://gitlab.com")
    private_token = os.getenv("GITLAB_TOKEN")
    
    if private_token:
        gl = gitlab.Gitlab(url=server_url, private_token=private_token)
    else:
        print(
            "[pychangeset:comment] No token found. Set GITLAB_TOKEN or CI_JOB_TOKEN.",
            file=sys.stderr,
        )
        return

    Comment(gl).run()
